// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UDI_kodetest_revised.Data;

#nullable disable

namespace UDI_kodetest_revised.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UDI_kodetest_revised.Models.Entity.Person", b =>
                {
                    b.Property<string>("Personnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fødselsdato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mellomnavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobilnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poststed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reisedokumentnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Personnummer");

                    b.ToTable("Personer", (string)null);
                });

            modelBuilder.Entity("UDI_kodetest_revised.Models.Entity.Sak", b =>
                {
                    b.Property<string>("SakId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Sakid");

                    b.Property<string>("FullmektigPersonnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KontaktPersonnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RecNo")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Recno");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SendtSms")
                        .HasColumnType("bit");

                    b.Property<string>("SoekerPersonnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VedtakId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SakId");

                    b.HasIndex("FullmektigPersonnummer");

                    b.HasIndex("KontaktPersonnummer");

                    b.HasIndex("SoekerPersonnummer");

                    b.HasIndex("VedtakId");

                    b.ToTable("Saker", (string)null);
                });

            modelBuilder.Entity("UDI_kodetest_revised.Models.Entity.Vedtak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GyldigFra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GyldigTil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vedtak", (string)null);
                });

            modelBuilder.Entity("UDI_kodetest_revised.Models.Entity.Sak", b =>
                {
                    b.HasOne("UDI_kodetest_revised.Models.Entity.Person", "Fullmektig")
                        .WithMany()
                        .HasForeignKey("FullmektigPersonnummer");

                    b.HasOne("UDI_kodetest_revised.Models.Entity.Person", "Kontakt")
                        .WithMany()
                        .HasForeignKey("KontaktPersonnummer");

                    b.HasOne("UDI_kodetest_revised.Models.Entity.Person", "Soeker")
                        .WithMany()
                        .HasForeignKey("SoekerPersonnummer");

                    b.HasOne("UDI_kodetest_revised.Models.Entity.Vedtak", "Vedtak")
                        .WithMany()
                        .HasForeignKey("VedtakId");

                    b.Navigation("Fullmektig");

                    b.Navigation("Kontakt");

                    b.Navigation("Soeker");

                    b.Navigation("Vedtak");
                });
#pragma warning restore 612, 618
        }
    }
}
